[workspace]
members = ["core", "app"]
resolver = "2"

[workspace.dependencies]
ndsr-core = { path = "core" }
binrw = "0.15.0"
serde = { version = "1.0.219", features = ["derive"] }
thiserror = "2.0.16"