[package]
name = "ndsr-core"
version = "0.1.0"
edition = "2024"

[dependencies]
binrw = { workspace = true }
modular-bitfield = { workspace = true }
png = { workspace = true }
thiserror = { workspace = true }